name: botones
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lorem: ^2.0.0
  flutter_lints: ^3.0.0
  english_words: ^4.0.0
  url_launcher: ^6.0.9

flutter:
  uses-material-design: true